SELECT e.DNI, e.FECHA AS "FECHA CONTRATACION", d.NOMBRE, d.DIRECCION 
	FROM empleados AS e
		JOIN dnis AS d 
			ON e.DNI = d.DNI
				WHERE d.NOMBRE LIKE "ANA";
				
				
UPDATE empleados SET FECHA = "2024-05-08 14:16:00";

UPDATE empleados SET FECHA = "2024-07-01 10:00:00" WHERE EMPLEADO_ID = 1;
